# Uncomment this line to define a global platform for your project
platform :ios, '10'

# ignore all warnings from all pods
inhibit_all_warnings!

def development
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Realm'
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Storage'
  pod 'Alamofire'
  pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'master'
end

target 'FirebaseTaco' do
  use_frameworks!
  development
end


